### ISSUE TITLE
App crashes if album have some special characters

### ISSUE THREAD

**Issue by Devaniti** [un33k/python-slugify#106]
```
Downloads: 10 items
Traceback (most recent call last):
  File "gparch_cli.py", line 138, in <module>
    account.download_all_albums()
  File "C:\Projects\ArchiverForGooglePhotos\gparch.py", line 315, in download_all_albums
    self.download_single_album(album)
  File "C:\Projects\ArchiverForGooglePhotos\gparch.py", line 362, in download_single_album
    album_path = auto_mkdir(self.albums_dir + "/" + album["title"])
  File "C:\Projects\ArchiverForGooglePhotos\gparch.py", line 73, in auto_mkdir
    os.mkdir(new_path)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Projects\\ArchiverForGooglePhotos/Albums/Demänovská Dolina: путешествие'
```

**Comment by Devaniti** [comment]
You should probably use something like python-slugify to replace title with something "safe" for filenames

**Comment by Devaniti** [comment]
Sorry, wrong repo
