### ISSUE TITLE
Slugify 6.1.0 breaks under Python 3.4.2 - ImportError: No module named 'typing'

### ISSUE THREAD

**Issue by samlehman** [un33k/python-slugify#112]
Hello,

So I'm using the library csvkit 1.0.5 on Python 3.4.2.

Here's my full backtrace:

```
File failed with error: StandardError: conversion failed: Traceback (most recent call last):
File "/usr/local/bin/in2csv", line 9, in <module>
load_entry_point('csvkit==1.0.5', 'console_scripts', 'in2csv')()
File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
return ep.load()
File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
['__name__'])
File "/usr/local/lib/python3.4/dist-packages/csvkit/__init__.py", line 15, in <module>
import agate
File "/usr/local/lib/python3.4/dist-packages/agate/__init__.py", line 5, in <module>
from agate.aggregations import *
File "/usr/local/lib/python3.4/dist-packages/agate/aggregations/__init__.py", line 21, in <module>
from agate.aggregations.count import Count
File "/usr/local/lib/python3.4/dist-packages/agate/aggregations/count.py", line 5, in <module>
from agate.utils import default
File "/usr/local/lib/python3.4/dist-packages/agate/utils.py", line 20, in <module>
from slugify import slugify as pslugify
File "/usr/local/lib/python3.4/dist-packages/slugify/__init__.py", line 2, in <module>
from .slugify import *
File "/usr/local/lib/python3.4/dist-packages/slugify/slugify.py", line 3, in <module>
import typing
ImportError: No module named 'typing'
```

I read that 'typing' is available in python 3.5 and on (https://stackoverflow.com/questions/67344483/importerror-no-module-named-typing-when-trying-to-install-a-package). 

So I suppose slugify might need to limit which version of python it can be installed under?

I think my solution to my issue might be to lock slugify to the previous version of slugify.

**Comment by un33k** [comment]
@samlehman I agree that every project needs to pin down the dependencies to provide stability. 

With that said, we are tracking the issue here. https://github.com/un33k/python-slugify/issues/110

**Comment by samlehman** [comment]
@un33k Great, thanks!
