### ISSUE TITLE
Error installing version 1.2.2 with buildout

### ISSUE THREAD

**Issue by ericdupo** [un33k/python-slugify#38]
Hello,

When installing version 1.2.2 with buildout I have this error : 
```

Getting distribution for 'python-slugify'.
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2270, in main
    **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-nJRC3I/python-slugify-1.2.2/setup.py", line 89, in <module>
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
An error occurred when trying to install /tmp/tmpN77DXmget_dist/python-slugify-1.2.2.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing eggs.
  Getting distribution for 'python-slugify'.
```

I do not have this problem when using version 1.2.1

**Comment by reece** [comment]
This isn't related to buildout. It is triggered by `bdist_egg`, but not `bdist`.

```
snafu$ cd /tmp
snafu$ wget -nd -q 'https://pypi.python.org/packages/30/81/866cf0efb431c1aef44fce68130756a8a5d0eeda0b20571b1db8bc54d2f3/python-slugify-1.2.2.tar.gz#md5=2856b79c41eca45a7198f950e395455c'snafu$ tar -xzf python-slugify-1.2.2.tar.gz 
snafu$ cd python-slugify-1.2.2/
snafu$ python setup.py bdist_egg
running bdist_egg
...
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    entry_points={'console_scripts': ['slugify=slugify.slugify:main']},
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

```

**Comment by un33k** [comment]
It may just be a corrupt build. I will bump the version and push another build soon.

**Comment by reece** [comment]
Thanks. FWIW, I fetch the github repo, built an sdist from 1.2.2, and compared it to the pypi tarball. The only difference was the ordering of keys in setup.cfg (which is probably a dict ordering variation).

It's hard to see how a new version will help, but I'm game to try. Thanks.

**Comment by reece** [comment]
@un33k The just-released 1.2.3 still contains __pycache__ and .pyc files (now for 3.4 and 3.6).

**Comment by un33k** [comment]
@reece thx for the feedback ...

**Comment by reece** [comment]
@un33k: 1.2.4 immediately resolved the build issues I was having at RTD. Thanks for jumping on this quickly! I think you can close this.

**Comment by un33k** [comment]
Yeah
