### ISSUE TITLE
submitting non-unicode to normalize chars in py2

### ISSUE THREAD

**Issue by grandrew** [un33k/python-slugify#69]
```
normalize() argument 2 must be unicode, not str
    Traceback (most recent call last):
      File "./gnib_par_pool.py", line 383, in screenshot
        screenshot(self.driver, str(ids)+str(self.sess))
      File "./gnib_par_pool.py", line 86, in screenshot
        driver.save_screenshot(slugify('%s-screenie-%s' % (datetime.datetime.now().isoformat(), str(sid),))+".png")
      File "/usr/local/lib/python2.7/dist-packages/slugify.py", line 26, in slugify
        unicodedata.normalize('NFKD', string)
    TypeError: normalize() argument 2 must be unicode, not str
```

saw this already at https://github.com/un33k/python-slugify/issues/35

happy to debug

the code works in pipenv but does not in ubuntu 16.04

there is something to do with ubuntu I guess

**Comment by grandrew** [comment]
workaround:

```
from slugify import slugify as slugify_orig

def slugify(s):
    return str(slugify_orig(unicode(s)))

```

**Comment by un33k** [comment]
@grandrew happy debugging and pls raise a PR if you find a bug/fix. thx
